<a href="https://colab.research.google.com/github/saberonjr/deeplearningpytorch/blob/main/Deep_Learning_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [ ]:
!pip list

# **Lists**

In [2]:
my_lists = [[1,2,3],[3,4,5]]
my_lists

[[1, 2, 3], [3, 4, 5]]

# **Numpy Arrays**

In [7]:
np1 = np.random.rand(3,4)
np1.dtype
np1

array([[0.23147933, 0.67954461, 0.89124191, 0.35512277],
       [0.016656  , 0.65467497, 0.20141353, 0.51033063],
       [0.96720368, 0.34546164, 0.68194465, 0.54885087]])

# **Tensors**

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.5077,  1.5557,  1.5039,  1.8857],
        [-0.1495, -0.6424, -1.1104, -1.5818],
        [-0.8876,  0.0903,  0.6357,  0.3788]])

In [8]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-1.3797,  1.2762, -0.8010,  1.3789],
         [ 0.2416, -1.6677, -0.9722,  1.9893],
         [-0.1429,  0.1482,  0.3485, -0.1503]],

        [[-1.0954, -0.0416, -1.1522,  0.4125],
         [-0.6805, -2.6933, -2.3917,  0.0864],
         [-1.1125,  0.5942,  0.0403, -0.5313]]])

In [10]:
#tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2315, 0.6795, 0.8912, 0.3551],
        [0.0167, 0.6547, 0.2014, 0.5103],
        [0.9672, 0.3455, 0.6819, 0.5489]], dtype=torch.float64)

# **Tensor Operations**

In [3]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and View
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch2 = torch.arange(18)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [14]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])

In [15]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch4 = my_torch3.view(2,-1)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch5 = my_torch4[:,1:4]
my_torch5

tensor([[1, 2, 3],
        [6, 7, 8]])

# **Tensor Math Operation**

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

tensor_c = tensor_a + tensor_b
tensor_c

tensor([ 6,  8, 10, 12])

In [3]:
tensor_d = torch.add(tensor_a, tensor_b)
tensor_d

tensor([ 6,  8, 10, 12])

In [4]:
tensor_e = tensor_b - tensor_a
tensor_e

tensor([4, 4, 4, 4])

In [5]:
tensor_f = tensor_a * tensor_b
tensor_f

tensor([ 5, 12, 21, 32])

In [6]:
tensor_g = tensor_b / tensor_a
tensor_g

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [7]:
tensor_f.dtype

torch.int64

In [8]:
tensor_g.dtype

torch.float32

In [9]:
tensor_h = tensor_b % tensor_a
tensor_h

tensor([0, 0, 1, 0])

In [11]:
tensor_i = tensor_a.pow(tensor_b)
tensor_i

tensor([    1,    64,  2187, 65536])

In [12]:
#Reassignment
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])